version: '4.13.1'
services:
  contactdb:
    container_name: contactdb
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - contactdb_volume:/data/db
  rabbitmq: 
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  contactapi:
    container_name: contactapi
    ports:
      - "5011:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://contactdb"
    depends_on:
      - contactdb
  reportapi:
    container_name: reportapi
    ports:
      - "5012:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - "DatabaseSettings:ConnectionString=mongodb://contactdb"
      - "ContactAPILocationDataListUrl=http://contactapi/api/ContactInformations/GetLocationDataList"
    depends_on:
      - rabbitmq
      - contactdb
      - contactapi
