version: '4.13.1'
services:
  contactdb:
    image: mongo
  rabbitmq: 
    image: rabbitmq:3.11.2-management
  contactapi:
    image: contactapi_image
    build:
      context: .
      dockerfile: Services/Phonebook.ContactAPI/Dockerfile
  reportapi:
    image: reportapi_image
    build:
      context: .
      dockerfile: Services/Phonebook.ReportAPI/Dockerfile
volumes: 
  contactdb_volume: